github_org_name: homelab

runner:
  image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:ubuntu-20.04
  ready: 3
  labels:
    - homelab

  env:
    - name: LOCATION
      value: "homelab"
