apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-deployment
spec:
  replicas: {{ .Values.runner.ready }}
  template:
    spec:
      image: {{ .Values.runner.image }}
      dockerdWithinRunnerContainer: true
      organization: {{ .Values.github_org_name }}
      {{- with .Values.runner.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.runner.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
